# Generated by Django 2.1.7 on 2019-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrName', models.CharField(max_length=50)),
                ('usrLastname', models.CharField(max_length=50)),
                ('usrPassword', models.CharField(max_length=50)),
                ('userVidSeen', models.ManyToManyField(to='courses.Videos')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
