# Generated by Django 2.1.7 on 2019-11-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidName', models.CharField(max_length=60)),
                ('vidTopic', models.CharField(max_length=70)),
                ('vidLength', models.CharField(max_length=50)),
                ('vidLecturer', models.CharField(max_length=50)),
                ('vidLanguage', models.CharField(max_length=50)),
                ('vidLocation', models.FileField(max_length=70, upload_to='')),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Category')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
